version: '3.9'

services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - frontend-bridge
    ports:
      - '5432:5432'
  arkesia-gg-web:
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - frontend-bridge
    ports:
      - '3000:3000'
      - '8002:8002'

networks:
  frontend-bridge:
